### create user
POST  http://localhost:3000/auth/register
Content-Type: application/json

{
  "email" : "Tole@gmail.com",
  "password": "123456",
  "username":"Tole"
}


### get user
GET   http://localhost:3000/users

### login user
POST    http://localhost:3000/auth/login
Content-Type: application/json

{
  "email":"Tole@gmail.com",
  "password":"123456"
}

